#!/usr/bin/env bash
# This is an OS X install-time hack
#@@INJECTPATH

TIMEOUT=20
VERSION="@@VERSION"
_uname="$(uname)"

tmp="$(python3 -c "import tempfile;print(tempfile.gettempdir())")"

[[ "$_uname" == "Darwin" ]] && \
    CONFIG="Library/Application Support" ||\
    CONFIG=".config"
CONFIG="${HOME}/${CONFIG}/sidechat"
SETTINGS="$CONFIG/settings"
[[ -e "$SETTINGS" ]] && source "$SETTINGS"

[[ -r "$CONFIG" ]] || mkdir -p "$CONFIG"
MDIR="$tmp"/sidechat
[[ -d "$MDIR" ]] || (mkdir "$MDIR" && chmod 0777 "$MDIR")
MDIR="$MDIR/$UID"
[[ -d "$MDIR" ]] || mkdir "$MDIR"
MDREAD='sd -c <(echo -e "[style]\nMargin = 4")'

load_pref() {
    [[ -e "$SETTINGS" ]] && source "$SETTINGS"
}
clean() {
    tput cnorm
}

ll() {
    local tool=()
    local system=()
    local dry=
    [[ "$TOOLS" == "ON" && "$CANTOOLS" == "0" ]] && tool=( "-tf" "$DIR/sc-tf.json" "-tp" "$DIR/sc-tp.py" "-mf" "$CONFIG/mcp.json" )

    if [[ -n "$NEWCONVO" ]]; then
        system=("-s" "$SYSTEM")
        NEWCONVO=
    fi

    [[ -n "$DRY" ]] && dry="--curlify"

    sc_pane="${pane_list[0]}" llcat $dry -c "$convo_id" "${tool[@]}" --timeout $TIMEOUT \
        -m "$LLM_MODEL" -bq result -u "$SERVER_URL" "${system[@]}" \
	      -sk "$(head -1 $SERVER_AUTH)" "$@" 2> >(cat >&2) 
}

spinner() {
    set +x
    tput civis
    trap clean EXIT SIGINT SIGTERM SIGQUIT
    SPINNER="⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏"

    i=0
    while [[ 0 ]]; do
      read -N 1 -t 0.05 tok
      [[ $? != 142 ]] && break
      printf "\e[2K${SPINNER:$i:1}\r"
      (( i = ( i + 1 ) % ${#SPINNER} ))
    done

    {
      echo -en "$tok"
      cat;
    } | ( [[ -n "$1" ]] && "$@" || cat )

    tput cnorm
}
