#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TOOLS=ON
CAPTURE="ON"
# Loads settings overrides
. $DIR/sc-_common
HISTFILE="$MDIR/history"
HISTSIZE=1000
INJECT=
MDREAD='sd -c <(echo -e "[style]\nMargin = 4")'
LLM_MODEL=
USECLIP=
LAUNCH="$0"
RETRY=
NEWCONVO=
CANTOOLS=0
DRY=
UNIQ=cat

tty=$(tty)
tmux list-panes -a -F '#{pane_tty}' 2>/dev/null | grep -qx "$tty"
INTMUX=$?
[[ "$INTMUX" == "1" ]] && INTMUX=

[[ "$_uname" == "Darwin" ]] && msize="-f %z" || msize="-c %s"
     
_warn() {
    echo -e "**⚠️** *$@*" | $MDREAD
}

show_params() {
    eval "$(tmux list-panes -a -F "#{pane_id}=#{pane_index}" 2> /dev/null | tr '%\n' '_;' )"
    {
        echo -n "  * **Shared:** [ "
        for _ix in "${pane_list[@]}"; do
            local v="${_ix/\%/_}"
            echo -n " ${!v}"
        done
        echo " ]"
    }
    if [[ "$#" -gt 0 && "$1" == "panes" ]]; then
        return
    fi
    echo -n "  * **Model**:  ${LLM_MODEL:-*(None Set)*}"
    [[ "$TOOLS" == "ON" ]] && echo " 🛠" || echo ""

    echo "  * **Server**: ${SERVER_URL:-*(Needs to be configured)*} (${TIMEOUT}s)"
    echo "  * **Keyfile**: ${SERVER_AUTH:-*(None)*}"

    local size="$(stat $msize "$convo_id")"
    echo "  * **Convo**:  ${convo_id} ($size B)"
    echo "  * **Config**: ${SETTINGS}"
}

help() {
  if [[ "$#" -gt 0 ]]; then 
    {
        echo "### Parameters  (*[sidechat $VERSION](https://github.com/day50-dev/sidechat)*)"
        echo "  * **System Prompt**:"
        echo "$SYSTEM" | sed 's/^/> /g'
        show_params
        echo -e "\n### Commands"

    } | $MDREAD
  fi
  cat <<END
  /choose   - Choose shared panes
  /clip     - Select text into the clipboard as context
  /mindwipe - Forget this crazy world and start over
  /sshot    - Raster screenshot
  /capture  - Toggle capture (now: $CAPTURE)
  cmd | sc-add [-c cid] [prompt] - Add the output of cmd to the context
END
  if [[ "$#" -ne 0 ]]; then 
cat <<END
  /amnesia  - Like mindwipe but take some ideas with you
  /model | /server | /key - change the {model, server, key}
  /prev     - Load a previous conversation
  /flash    - Flash the shared panes
  /upgrade  - Self-upgrade
  /retry    - Try the last request again
  /tools    - Toggle Tools (now: $TOOLS)
  /edit     - Edit the internal state
  /timeout  - Set the timeout
END
  fi
}

nlchomp() {
  [[ "$_uname" == "Darwin" ]] && awk '{printf "%s, ", $0} END{print ""}' || { sed -z 's/\n/, /g' | sed -E 's/, $//' ; }
}

sys_prompt() {

    # Try to not use contractions to keep escaping clean
    SYSTEM="You are an interactive buddy in tmux talking to a competent engineer whose instincts are better than yours. If they disagree with you, trust them and do not argue. Your job is mostly either small things like syntax or arcane knowledge. It is generally not architecture or design. Assume they have already tried what a competent engineer would do. You will get capture-pane -p followed by questions when the pane output changes. Run tools when appropriate. They are using $(uname -ar). Notices come to you like (Note: <message>). They can do the following: $(help | nlchomp)"

    if [[ -n "$EDITOR" ]]; then
        SYSTEM="$SYSTEM. The users editor is set to $(basename $EDITOR)"
    fi

    if [[ -s "$CONFIG/memories.json" ]]; then
        SYSTEM="$SYSTEM. User memories are [ $(jq -r ".[]" "$CONFIG/memories.json" | sed -E 's/your?\s/user /ig' | nlchomp ) ]"
    fi
}

onload() {
    [[ -r $HOME/.local/bin/sd ]] && MDREAD=$HOME/.local/bin/sd
    [[ -f "$HISTFILE" ]] || touch "$HISTFILE"

    [[ -e "$CONFIG/mcp.json" ]] ||  echo '{"mcpServers": {}}' | jq -r .  > "$CONFIG/mcp.json"

    history -r "$HISTFILE"
    trap 'history -w "$HISTFILE"' EXIT

    sys_prompt

    [[ -n "$INTMUX" ]] && my_id=$(tmux display-message -p '#{pane_id}') || my_id=

    pane_id=${1-}
    pane_list=( $pane_id )
    convo_id=
    forcecapture=
    debug=
    if [[ -r "$MDIR/${pane_id}.convo" ]]; then 
        convo_id=$(cat "$MDIR/${pane_id}.convo")
    fi
    if [[ -z "$convo_id" ]]; then 
        newconvo 
    else
        flash 1
    fi

    touch "$MDIR/${pane_id}.convo"
    touch "$MDIR/${pane_id}.old"

    load_pref
    set_prompt

    ata=""
    if [[ -n "$convo_id" ]]; then
        last 5
    else
        echo "Conversation Start: Type /help for options"
    fi
}

update() {
    tmux split-window -v "curl -s https://day50.dev/sidechat | sh; tmux wait-for -S upgrade"
    tmux wait-for upgrade
    echo -e "## And now the magical in-place upgrade\n" | $MDREAD
    exec "$LAUNCH" $pane_id
}
upgrade() {
    update
}

flash() {
    [[ -z "$1" ]] && show_params panes | $MDREAD
    if [[ -n "$INTMUX" ]]; then
        for ix_pane in "${pane_list[@]}"; do
            tmux select-pane -t $ix_pane -P 'bg=colour95'; sleep 0.03
            tmux select-pane -t $ix_pane -P 'bg=color129'; sleep 0.03
            tmux select-pane -t $ix_pane -P 'bg=default' 
        done
        tmux select-pane -t $my_id
    fi
    set_prompt
}

retry() {
    RETRY=1
}

save_pref() {
    local vname="$1"
    local stanza="$vname='$2'"
    local tmp="${SETTINGS}.tmp"
    [[ -d "$CONFIG" ]] || mkdir "$CONFIG"
    [[ -e "$SETTINGS" ]] || touch "$SETTINGS"
    { grep -vE "^${vname}=" "$SETTINGS" ; echo "$stanza"; } > "$tmp"
    mv "$tmp" "$SETTINGS"
    eval "$stanza"
}

key() {
    local input
    echo "The auth token should point to a file where it's the first line"
    read -p "  Enter path: " input
    input=${input/#\~/$HOME}
    SERVER_AUTH=$input
    save_pref SERVER_AUTH "$SERVER_AUTH"
}

server() {
    local SERVER_URL_
    local input="$1"
    if [[ -z "$input" ]]; then
        {
            echo -e "The server URL:\n"
            echo " * Should include the schema, such as \`http://\` or \`https://\`"
            echo " * Be OpenAI compatible (e.g., litellm/llama.cpp/ollama/openrouter/etc)"
            echo " * Can be some special values: "
            echo "   * \`[MAS format](https://day50.dev/mas.html)\` - http://(host)#m=(model)"
            echo "   * \`prev\`   - choose from prior servers"
            echo "   * \`or\`     - openrouter"
            echo "   * \`ollama\`  - ollama    (local)"
            echo -e "   * \`llama\`  - llama.cpp (local)\n"
        } | $MDREAD
        builtin read -p "  Enter URL: " input
    fi
    if [[ -n "$input" ]]; then
        case $input in 
            prev) SERVER_URL_="$(cat "$CONFIG"/servers.txt | fzf | cut -d ' ' -f 1)" ;;
            or) getkey=1; SERVER_URL_=https://openrouter.ai/api ;;
            ollama) SERVER_URL_=http://localhost:11434 ;;
            llama) SERVER_URL_=http://localhost:8080 ;;
        esac
        SERVER_URL="$input"
        if [[ -n "$SERVER_URL_" ]]; then
            echo -e " Using \`$SERVER_URL_\`" |$MDREAD
            SERVER_URL="$SERVER_URL_"
        fi

        if [[ ! "${SERVER_URL@L}" =~ "http" ]]; then
            _warn "This is a very unusual url, testing...\n"
            if ! llcat -u $SERVER_URL -m > /dev/null; then
                echo -e "\n  Yep! Thought so, let's try this again!\n"
                server
            fi
        fi
            
        if [[ "${SERVER_URL}" =~ "#m=" ]]; then
            LLM_MODEL="${SERVER_URL#*#m=}"
            SERVER_URL="${SERVER_URL%%#m=*}"
            model "$LLM_MODEL"
        fi

        touch "$CONFIG/servers.txt" 
        grep -c "$SERVER_URL" "$CONFIG/servers.txt" > /dev/null || echo "$SERVER_URL" >> "$CONFIG/servers.txt"
        save_pref SERVER_URL "$SERVER_URL"
        if [[ -n "$getkey" && -z "$SERVER_AUTH" ]]; then
            echo
            key
        fi
        if [[ "$SERVER_URL" =~ 11434 ]]; then
            echo "Currently running **"$(curl -s "$SERVER_URL"/api/ps | jq -r '.models[0].name')"**. (null is good)" | $MDREAD
        fi
    else
        _warn "Cancelled"
    fi
}

check() {
    if [[ "$1" =~ (server|both) && -z "$SERVER_URL" ]]; then 
        _warn "You need to set a server before continuing"
        echo
        server
    fi
    if [[ "$1" =~ (model|both) && -z "$LLM_MODEL" ]]; then 
        model
    fi
}

model() {
    check server
    local _fzf=fzf-tmux

    if [[ -n "$1" ]]; then
        chosen="$1"
    else
        [[ -z "$INTMUX" ]] && _fzf=fzf
        chosen=$(llarg -m | sort | $_fzf )
    fi    

    if [[ -n "$chosen" ]]; then

      echo " * Setting model to \`$chosen\`." | $MDREAD
      save_pref LLM_MODEL "$chosen"

      touch "$CONFIG/servers.txt"
      if ! grep "$LLM_MODEL" "$CONFIG/servers.txt" | grep -c $SERVER_URL > /dev/null; then
          perl -i -pe "s^($SERVER_URL.*)^\$1 $LLM_MODEL^g" "$CONFIG/servers.txt"
      fi
     
      #echo " * Checking for tool support..." | $MDREAD
      #[[ -z "$LLM_MODEL" ]] && { _warn "Model unset"; return; }

      #llcat -u "$SERVER_URL" -m "$LLM_MODEL" --info | grep tool > /dev/null
      #CANTOOLS=$?
      #save_pref CANTOOLS "$CANTOOLS"
      #toolhack
      CANTOOLS=0
    fi
}

models() {
    model
}

set_prompt() {
    local camera=""
    local clipboard=""
    local tools=""
    [[ "$TOOLS" == "ON" ]] && tools="🔧"
    [[ -n "$INTMUX" && "$CAPTURE" == "ON" ]] && camera="📷"
    [[ -n "$USECLIP" ]] && clipboard='📋'
    prompt="${camera}${tools}${clipboard} > "
}

edit() {
    local _cat=$(command -v batcat || command -v cat)
    local _edit=${EDITOR:-vi}

    local fname=$(
        {
         sd --help | grep '^  config' | rev | cut -d ' ' -f 1 | rev;
         echo $convo_id;
         echo "$SETTINGS"
         echo "$CONFIG/memories.json"
         echo "$CONFIG/mcp.json"
         echo "$CONFIG/servers.txt";
        } | fzf --style full --preview "$_cat {}"
    )
    [[ -z "$fname" ]] && _warn Cancelled || $_edit "$fname"
}

choose() {
    forcecapture=1
    local depth=${1:-0}
    [[ "$depth" == 0 ]] && echo "Select panes or any other key to end selection" | $MDREAD
    [[ -z "$INTMUX" ]] && return
    tmux display-panes -d 0 "run-shell 'echo %% > $MDIR/pane-id'"

    if [[ $? == "1" ]] ; then
        echo "Exiting due to possible infinite loop."
        exit 1
    fi

    if [[ -e "$MDIR/pane-id" ]]; then 
        pane_id=$(cat "$MDIR/pane-id")
        [[ "$depth" == 0 ]] && pane_list=( )
        pane_list+=( $pane_id )
        (( depth ++ ))
        flash
        rm "$MDIR/pane-id"
        tmux select-pane -t $my_id
        touch "$MDIR/${pane_id}."{convo,old}
        INJECT=" (Note: User changed tmux panes)"

        # If you're choosing something you probably also want to capture
        # I had forgotten the flow and was running choose a few times 
        # wondering why it wasn't capturing
        choose "$depth"
    else
        [[ "$depth" == "0" ]] && echo "Cancelled" 
        return 1
    fi
    if [[ "$CAPTURE" == "OFF" ]]; then
        capture
    fi
    read -t 0.05 -n 1
    return 0
}

getlast(){
    local wid=$(( $(tput cols) / 2 ))
    {
        cd $MDIR
        fzf --disabled \
            --bind 'start:reload:find . -type f -size +0c -name c\*' \
            --bind 'change:reload:grep -l {q} c* || true' \
            --style full --preview "sd -w $wid <(jq -r '.[] | select(.role != \"system\") | \"\n**\(.role)**: \(.content)\"' \"$MDIR\"/{} | tail -40)";
    }
}

prev() {
    choice=$(getlast)
    if [[ -z "$choice" ]]; then
        _warn "Cancelled"
    else
        convo_id="$MDIR/$choice"
        echo "$convo_id" > "$MDIR/${pane_id}.convo"
        last
    fi
}

toolhack() {
    if [[ "$CANTOOLS" == 1 && "$TOOLS" == "ON" ]]; then
        echo ' * No formal toolcall support. Using the hack! ' | $MDREAD
        sys_prompt
        save_pref TOOLS "ON"
        SYSTEM+=". IMPORTANT: To call tools Respond only with the json '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/call\",\"params\":{\"name\":\"<insert function name>\",\"arguments\":{<insert paramaters here>}}}'. You will get the response in the reply. Here are the tools you can call $(jq -r '.[].function' "$DIR/sc-tf.json" | tr "\n" " " | sed -E "s/\s+/ /g")"
        # force system-prompt re-injection
        NEWCONVO=1
    fi
}

tools() {
    [[ "$TOOLS" == "ON" ]] && TOOLS="OFF" || TOOLS="ON"
    _warn "Tools are ${TOOLS@L}" 
    save_pref TOOLS "$TOOLS"
    toolhack
}

last() {
    amount=${1:-40}
    { 
        show_params; 
        echo -e "\n------\n"; 
        jq -r '.[] | "\n**\(.role)**: \(.content)"' $convo_id | tail -$amount; 
    } | $MDREAD
}

llc() {
    ll -m "$LLM_MODEL" "$@"
}

newconvo() {
    day=$(date +%m%d-%H%M)
    convo_id=$(mktemp "$MDIR/c-$day-XXXX")
    echo $convo_id > "$MDIR/${pane_id}.convo"
    _warn "New convo is $convo_id"
    NEWCONVO=1
}

amnesia() {
    newconcepts=$(llc 'list out all the desires of this conversation as a json array following the format "User wants to " followed by a description of what the user wants to do. Also list the topics in the format "Topic is..." and if there are open or difficulties "We are working on...". If the user has specified preferences list those as well.' | grep -Ev '(```|\[|\])' | fzf --multi)
    newconvo
    echo "Injecting: $newconcepts" | $MDREAD
    llc "$newconcepts" | $MDREAD
}

mindwipe() {
    sys_prompt
    newconvo
    forcecapture=1
}

capture() {
    if [[ "$CAPTURE" == "ON" ]]; then
        echo "Capturing off. Shades are drawn!"
        save_pref "CAPTURE" "OFF"
        INJECT="$INJECT (Note: User turned capture off)"
    else
        if [[ -n "$INTMUX" ]]; then
          while ! tmux list-panes -t "$pane_id" &>/dev/null; do
              echo "Woops, the pane disappeared. Choose another!"
              choose
          done

          flash
          echo "Capturing on. I see you!"
          INJECT="$INJECT (Note: User turned capture on)"
        else
          echo "No TMUX... No capture"
        fi
        save_pref "CAPTURE" "ON"
    fi
}

clip_nvim() {
    nvim --headless --cmd "echo getreg('+')" --cmd "qa" 2>&1
}


clip() {
    USECLIP=
    local xclip=$(command -v xclip)
    local nvim=$(command -v nvim)
    local pbpaste=$(command -v pbpaste)
    local emacs=$(command -v emacsclient) 

    if [[ -n "$xclip" ]]; then
        for i in p c s; do 
            xclip -o -${i} > "$MDIR/clip.$i"
        done
    fi

    tmux show-buffer > "$MDIR/clip.tmux" 2> /dev/null

    if [[ -n "$pbpaste" ]]; then
       pbpaste > "$MDIR/clip.pbpaste"
    fi

    if [[ -n "$nvim" ]]; then
       clip_nvim > "$MDIR/clip.nvim"
    fi

    if [[ -n "$emacs" ]]; then
        emacsclient --eval '(current-kill 0)' > "$MDIR/clip.emacs" 2>/dev/null
    fi

    {
        echo "Select the text you want to send and I'll find out what clipboard it is, hopefully..."
        echo -n 'Supported: `tmux` '
        [[ -n "$nvim" ]]    && echo -n '`nvim` '    || echo -n '~~`nvim`~~ '
        [[ -n "$pbpaste" ]] && echo -n '`pbpaste` ' || echo -n '~~`pbpaste`~~ '
        [[ -n "$xclip" ]]   && echo -n '`xsel` '     || echo -n '~~`xsel`~~ '
        [[ -n "$emacs" ]]   && echo -n '`emacs` '    || echo -n '~~`emacs`~~ '
        echo
        echo
    } | $MDREAD
    
    while [[ 0 ]]; do
        if [[ -n "$xclip" ]]; then
            for i in p c s; do 
                if ! diff <(xclip -o -${i}) "$MDIR/clip.$i" > /dev/null; then
                    USECLIP="xclip -o -${i}"
                    break 2
                fi
            done
        fi

        if [[ -n "$emacs" ]]; then
            if ! diff <(emacsclient --eval '(current-kill 0)' 2>/dev/null) "$MDIR/clip.emacs" > /dev/null; then
                USECLIP="emacsclient --eval '(current-kill 0)' 2>/dev/null"
                break
            fi
        fi

        if [[ -n "$pbpaste" ]]; then
            if ! diff <(pbpaste) "$MDIR/clip.pbpaste" > /dev/null; then
                USECLIP=pbpaste
                break
            fi
        fi

        if [[ -n "$nvim" ]]; then
            if ! diff <(clip_nvim) "$MDIR/clip.nvim" > /dev/null; then
                USECLIP=clip_nvim
                break
            fi
        fi
        if ! diff <(tmux show-buffer 2>/dev/null) "$MDIR/clip.tmux" > /dev/null; then
            USECLIP="tmux show-buffer"
            break
        fi
        sleep 0.3
    done

    if [[ -n "$USECLIP" ]]; then
        {
            echo -e "\nFound!\n### Next prompt will use \`$USECLIP\`"
        } | $MDREAD
    else
        echo "Aborted"
    fi
}

timeout() {
    if [[ -n "$1" ]]; then
        TIMEOUT="$1"
        save_pref TIMEOUT $TIMEOUT
        echo "Timeout set to $TIMEOUT"
    else
        echo "Cancelled"
    fi
}

emit_capture() {
    local ix=$1
    echo " has_changed=True>"
    [[ -n "$INTMUX" && -s "$MDIR/${ix_pane}.new" ]] && _pid=$(tmux display -pt "$ix" '#{pane_pid}')

    if [[ "$_uname" == "Linux" && -n "$INTMUX" ]]; then
        echo "<ps hierarchy>IMPORTANT: This is what is currently running: $(ps -o comm= --ppid $_pid -p $_pid | tr '\n' ' '). YOU DO NOT NEED TO RUN IT AGAIN, IT IS ALREADY RUNNING.</ps hierarchy>"
    fi
    echo "<capture>"
    cat "$MDIR/${ix}.new" | sed -e :a -e '/^\n*$/{$d;N;ba}'
    echo "</capture>"
}

process_out() {
    read -r -N 1 firstc
    if [[ "$firstc" == "{" ]]; then
        echo "Running tool"
        {
            echo '{"jsonrpc":"2.0","id":0,"method":"initialize","params":{"protocolVersion":"2024-11-05","capabilities":{},"clientInfo":{"name":"mcpcat","version":"1.0"}}}'
            echo -n "{";
            cat
        } > $MDIR/tc-input 
        cat $MDIR/tc-input | tr "'" '"' | "$DIR/sc-tp.py" > $MDIR/tc-output
        echo "Feeding it back..."
        {
            echo "This is the result of the tool call:"
            echo "\`\`\`"
            cat "$MDIR/tc-output"
            echo "\`\`\`"
            echo "You can call an additional tool. If you are done calling tools, respond in normal written english."
        } | llc | spinner process_out
    else
        {
            echo -n "$firstc"
            cat 
        } | $MDREAD
    fi
}

onload $@

while [ 0 ]; do 
    echo
    input=""
    pline="$prompt"
    while IFS= read -rep "$pline" line || exit; do
        if [[ "$line" == *\\ ]]; then
            input+="${line%\\}"
            input+=$'\n'
        else
            input+="$line"
            break
        fi
        pline="   |  "
    done
    [[ -z "$input" ]] && continue
    echo 

    _uuid=$(date +%s.%N)

    history -s "$input"  # Save to history
 
    if [[ $input =~ ^/ ]]; then
        if [[ $input == '/debug' ]]; then
            if [[ -n "$debug" ]]; then
                _warn "Debug Off"
                debug=; set +x; 
                export LOGLEVEL=
            else
                _warn "Debug On"
                debug=1; set -x; 
                export LOGLEVEL=debug
            fi
        elif [[ $input =~ ^/sshot ]]; then
            sshot=$(mktemp --suffix=.png -p "$MDIR")
            import $sshot
            ata="-a $sshot"
            echo "Next prompt will use your screenshot"
        elif [[ $input =~ (timeout|choose|clip|capture|edit|flash|key|amnesia|mindwipe|model|prev|retry|server|tools|upgrade|update) ]]; then
            if [[ "$intput" == *" "* ]]; then
                ${input:1} "${input#* }"
            else
                ${input:1}
            fi
        else
            help 1
        fi
        set_prompt
        # if we are retrying the last we want the same everything
        [[ -z "$RETRY" ]] && continue
    else
        text="$input"
    fi

    if [[ -z "$USECLIP" && $CAPTURE == "ON" && -n "$INTMUX" ]]; then
        for ix_pane in "${pane_list[@]}"; do
          tmux capture-pane -t "${ix_pane}" -p > "$MDIR/${ix_pane}.new"
          [[ -s "$MDIR/${ix_pane}.new" ]] || echo "**WARNING: Can't capture ${ix_pane}, Use /choose to update**" | $MDREAD
        done
    fi
    
    # If we get here now we know to be picky about if there's a model and a server
    check both
    n=0
    in="$MDIR/${convo_id}_${_uuid}"
    {
       if [[ -n "$USECLIP" ]]; then
           echo "<clipboard>"
           $USECLIP
           echo "</clipboard>"
       elif [[ "$CAPTURE" == "ON" ]]; then
         for ix_pane in "${pane_list[@]}"; do
            echo -n "<pane id=$ix_pane"
            if [[ -n "$RETRY" ]]; then
                cp "$MDIR/${ix_pane}.old" "$MDIR/${ix_pane}.new"
                emit_capture "$ix_pane"
            else
                if [[ -e "$MDIR/${ix_pane}.old" && -z "$forcecapture" ]]; then
                    /usr/bin/diff "$MDIR/${ix_pane}.new" "$MDIR/${ix_pane}.old" > /dev/null && echo -n " has_changed=False>" || emit_capture "$ix_pane"
                else
                    emit_capture "$ix_pane"
                fi
            fi
            echo "</pane>"
         done
      fi
    } | $UNIQ | {
        # only update the snapshot if the llc is successful
        if llc $ata "${text}${INJECT}"; then 
            for ix_pane in "${pane_list[@]}"; do
                [[ -e "$MDIR/${ix_pane}.new" ]] && cp "$MDIR/${ix_pane}.new" "$MDIR/${ix_pane}.old"
            done
        fi
    } | spinner process_out 

    # Needs to be run here and not in any subshell
    RETRY=
    INJECT=
    ata=""
    [[ -n "$USECLIP" ]]      && USECLIP=
    [[ -n "$forcecapture" ]] && forcecapture=
    set_prompt
done
